export const headerConfig = {
    UAC: [
        "Type",
        "UAC ID",
        "Date de création UAC",
        "Numéro du document",
        "Code d'organisation",
        "Unknown",
        "Unknown1",
        "Unknown2",
        "Adresse",
        "Adresse ou téléphone",
        "Unknown3",
        "Code Postal",
        "Ville",
        "Pays",
        "Date de début",
        "Date de fin",
    ],
    ACK: [
        "Type",
        "ACK ID",
        "Date de création ACK",
        "Type de référence",
        "UAC ID",
        "Date de création UAC",
        "Code d'organisation",
        "Unknown",
        "Unknown2",
        "Unknown3",
    ],
    ANM: [
        "Type",
        "ANM ID",
        "Date de création ANM",
        "Numéro du document",
        "UAC ID",
        "Date de création UAC",
        "Document ID",
        "Code d'organisation",
        "Unknown",
        "Unknown1",
        "Unknown2",
        "Unknown3",
        "Unknown4",
        "Description",
        "Unknown5",
        "Document Associé",
        "Type de référence",
    ],
    CRM: [
        "Type",
        "CRM ID",
        "Date de création CRM",
        "Numéro du document",
        "UAC ID",
        "Date de création UAC",
        "Document ID",
        "Code d'organisation",
        "Unknown",
        "Unknown1",
        "Unknown2",
        "Unknown3",
        "Type de référence",
    ],
};
